title: CXYZ的博客
description: 从 Obsidian 直接发布的博客
url: https://cuixyz.github.io

remote_theme: pages-themes/minimal@v0.2.0

permalink: /:title/

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

logo: /assets/logo.png
show_downloads: false
