encoding: utf-8
title: CX的时间戳
description: 从ob发布的博客
url: https://chron.cuixyz.cc

remote_theme: pages-themes/minimal@v0.2.0

permalink: /:year/:title/

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist

logo: /assets/logo.png
show_downloads: false
